[phases.setup]
nixPkgs = ["...", "ffmpeg"]
aptPkgs = ["..."]

[phases.build]
cmds = ["..."]

[phases.fix]
cmds = ["apt-get update && sudo apt-get install -y libsndfile1 libsndfile1-dev"]
dependsOn = ["build"]