[phases.setup]
nixPkgs = ["...", "ffmpeg"]
aptPkgs = ["...", "libsndfile1"]

[phases.build]
cmds = ["sudo apt-get update && sudo apt-get install -y libsndfile1 && sudo apt-get install -y libsndfile1-dev", "..."]